[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/TheFixer.TheFixerGameMode

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.AllowStaticLighting=False

[/Script/Engine.PhysicsSettings]
; Chaos vehicles want async fixed-tick physics for stable suspension.
bTickPhysicsAsync=True
AsyncFixedTimeStepSize=0.016667
